### ISSUE TITLE
Implement "merged doctests" to save doctest time

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#111]
| Metadata      | |
| --------      | --- |
| Owner(s)      | @GuillaumeGomez |
| Team(s)       | [rustdoc](https://github.com/rust-lang/rust) |
| Goal document | [2024h2/merged-doctests](https://rust-lang.github.io/rust-project-goals/2024h2/merged-doctests.html) |

## Summary

Implement "merged doctests" to save doctest time

## Tasks and status

* [x] Implementation (@GuillaumeGomez) https://github.com/rust-lang/rust/pull/126245
* [ ] Standard reviews ([rustdoc](https://github.com/rust-lang/rust) ![Team][])

[Team]: https://img.shields.io/badge/Team%20ask-red

**Comment by nikomatsakis** [comment]
This issue is intended for status updates only.

For general questions or comments, please contact the owner(s) directly.

**Comment by GuillaumeGomez** [comment]
The PR is implemented, tested and complete. We're still waiting for one of the three remaining reviewers to review. I have no idea how to unblock this situation.

**Comment by GuillaumeGomez** [comment]
The PR was merged and will be enabled by default in the 2024 edition. I think it can be closed.
