### ISSUE TITLE
The shield in slate.md says "Owned needed"

### ISSUE THREAD

**Issue by PoignardAzur** [rust-lang/rust-project-goals#16]
The shield before the sentence "We would also like to do the following but currently lack owners" currently says "Owned needed". Should point to a new shield without the typo.

Or better yet, use regular markdown formatting instead of a link to an image.

**Comment by lqd** [comment]
Fixed in https://github.com/rust-lang/rust-project-goals/pull/13

**Comment by PoignardAzur** [comment]
"What is the secret to open source", they ask me?

"Good timing", I tell them.
