### ISSUE TITLE
No link to "send bound" problem

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust-project-goals#19]
There's two spots in `async_fn_everywhere` that try to link to `[sb]`, but there isn't a corresponding `[sb]: https://....` definition. I would fix this myself, but I don't know where this should link to 😅 

The spots:

- https://github.com/rust-lang/rust-project-goals/blob/db56b08a87a4bc663027204facd0dfdbdadb6117/src/2024h2/async_fn_everywhere.md#L34
- https://github.com/rust-lang/rust-project-goals/blob/db56b08a87a4bc663027204facd0dfdbdadb6117/src/2024h2/async_fn_everywhere.md#L109

**Comment by lqd** [comment]
I *think* these links are about https://github.com/rust-lang/rfcs/pull/3654

**Comment by traviscross** [comment]
Also: https://smallcultfollowing.com/babysteps/blog/2023/02/01/async-trait-send-bounds-part-1-intro/

**Comment by lqd** [comment]
That is indeed what the now open async project goal RFC links to, [here](https://github.com/nikomatsakis/rfcs/blob/async-project-goal/text/0000-async-project-goal-2024h2.md#resolve-the-send-bound-problem). 

Apparently this page has been rewritten for the RFC and this link has been fixed.

**Comment by nikomatsakis** [comment]
fixed I think

**Comment by nikomatsakis** [comment]
Wait, no, I fixed it in the RFC :)

**Comment by nikomatsakis** [comment]
I should probably just redirect that page to the RFC

**Comment by nikomatsakis** [comment]
done.
