### ISSUE TITLE
Team confirmation for "cargo script" goal

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-project-goals#22]
Hi @rust-lang/cargo -- @epage proposed a [cargo script team goal](https://rust-lang.github.io/rust-project-goals/2024h2/cargo-script.html). I am following a process wherein approving a team goal requires the team lead (@ehuss) to leave a comment approving it. One option is to do `@rfcbot fcp merge`, but I don't consider it a requirement (e.g., I know this has been under discussion a long time).

**Comment by ehuss** [comment]
yep! It's approved.

**Comment by nikomatsakis** [comment]
Thanks @ehuss
